site_name: Buildarr Jellyseerr Plugin

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

markdown_extensions:
  - toc:
      permalink: "#"
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Release Notes: "release-notes.md"
  - Configuration:
    - Host Configuration: "configuration/host.md"
    - Settings:
      - General: "configuration/settings/general.md"
      - Users: "configuration/settings/users.md"
      - Jellyfin: "configuration/settings/jellyfin.md"
      - Services:
        - Sonarr: "configuration/settings/apps/sonarr.md"
        - Radarr: "configuration/settings/apps/radarr.md"
      - Notifications: "configuration/settings/notifications.md"
  - Buildarr: "https://buildarr.github.io"
  - GitHub: "https://github.com/buildarr/buildarr-jellyseerr"

watch:
  - buildarr_jellyseerr
